### ISSUE TITLE
Questions: Is that away to have different theme for different mode?

### ISSUE THREAD

**Issue by thyeun** [protesilaos/modus-themes#123]
By not using hook for different mode, just using modus configuration to control each mode with different theme?

Meaning that not using the below code to get change on theme when the mode are change.
```
(add-hook 'xxxx-mode-hook
   (lambda ()
      (load-theme "modus-theme" t t)
   ))
```

**Comment by protesilaos** [comment]
> From: Thomas Yeun ***@***.***>
> Date: Wed, 13 Nov 2024 07:04:54 -0800
>
> By not using hook for different mode, just using modus configuration to control each mode with different theme?
>
> Meaning that not using the below code to get change on theme when the mode are change.
> ```
> (add-hook 'xxxx-mode-hook
>    (lambda ()
>       (load-theme "modus-theme" t t)
>    ))
> ```

This cannot be done with themes because they are always global in Emacs.
What you can do is rely on the face remap feature. However, you will
need to define new faces for everything and handle all the remappings
for the result to be decent. I can show you how, if you are interested
but be prepared for a lot of custom code.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by thyeun** [comment]
Thanks for clear my doubt. look like the one easy way is to using the ```add-hook``` method for each mode to have different theme.
