### ISSUE TITLE
feature request: explicitly load theme

### ISSUE THREAD

**Issue by gitrj95** [protesilaos/modus-themes#13]
hi prot, i hope you are well

i was just wondering if you could add (interactive) to the load-operandi and load-vivendi functions, so they may be explicitly accessed by eg M-x

**Comment by protesilaos** [comment]
> hi prot, i hope you are well

Hello!  I'm doing well in terms of health, which is what matters right
now.  Other areas could use a drastic improvement, but we'll have to
manage.

Hope you're fine.

> i was just wondering if you could add (interactive) to the
> load-operandi and load-vivendi functions, so they may be explicitly
> accessed by eg M-x

I thought `M-x load-theme` was sufficient for that use-case.  But
apparently it is not enough, because it then prompts for a theme.

I guess we have two options here:

1. Add an `(interactive)` spec to the functions
   `modus-themes-load-operandi`, `modus-themes-load-vivendi`.

2. Document how the user can achieve that with some simple tweaks in
   their own init.

Example that covers both cases:

```elisp
(defun modus-themes-load-operandi ()
  "Load `modus-operandi' and disable `modus-vivendi'.
Also run `modus-themes-after-load-theme-hook'."
  (interactive)
  (disable-theme 'modus-vivendi)
  (load-theme 'modus-operandi t)
  (run-hooks 'modus-themes-after-load-theme-hook))
```

What do you think?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by gitrj95** [comment]
hi, prot. good to hear that you are in good health, and i hope those other areas improve, soon

i prefer (1), simply because it seems more ergonomic. eg, it would be nice to use use-package semantics to bind load-operandi and load-vivendi in a similar manner to that for toggle

**Comment by protesilaos** [comment]
I just pushed the change.  Please let me know how it goes.

**Comment by gitrj95** [comment]
looks great. thanks

**Comment by protesilaos** [comment]
Thank you!  Closing this issue then.
