### ISSUE TITLE
Placing cursor on matched characters `{`, `}`, `(`, `)` etc. causes the character to dissappear

### ISSUE THREAD

**Issue by sidkshatriya** [protesilaos/modus-themes#17]
I'm using emacs 29.0.50, with modus operandi 2.0.0 with pgtk (pure gtk). (BTW I am able to repeat the issue with emacs 28.0.90 also)

When I place my cursor on a character which matches e.g. `{`, `}`, `(`, `)`, `<`, `>`, the character becomes invisible and I can only see the cursor. I need to move my cursor away to reveal the character again.

My expectation is that the character should still display, even though the cursor is on it.

<img src="https://user-images.githubusercontent.com/638477/147544973-2bc7878a-bdd3-47fa-9960-05fca23c653d.png" width=200 />

This might be a strange interaction with spacemacs. I'm not sure what is causing this issue.

**Comment by protesilaos** [comment]
Hello @sidkshatriya!  Is your cursor that orange block in the screenshot?  The default cursor is black.

I actually zoomed in to your screenshot and could see a faint silhouette of `(`.  Which means that the problem is as follows:

* By default, the background colour of matching parentheses is a shade of orange as can be seen in the `)` on line 350.

* When the cursor is over the matching delimiter (or generally any background) it inverts the background/foreground combination.  So the foreground of the matching parenthesis is that shade of orange.

* Because your cursor is also orange, the character is no longer legible.

> This might be a strange interaction with spacemacs. I'm not sure what is causing this issue.

Have you customised the `cursor` face?  Otherwise yes, that is a Spacemacs thing in which case I am not sure what needs to be done.  I can try to help, but I am not familiar with Spacemacs.

Notwithstanding this bug, the `modus-themes-paren-match` variable can be customised to make the matching delimiters more intense.  For example:

```elisp
(setq modus-themes-paren-match '(bold underline intense))
```

There are several stylistic variations.  The variable's doc string (or the corresponding entry in the manual) covers the details.

**Comment by sidkshatriya** [comment]
> Is your cursor that orange block in the screenshot? The default cursor is black.

Yes, orange is color of my cursor.

> Have you customised the cursor face?

No I haven't. Yes, this is possible that this is something that is due to spacemacs, then.

```elisp
(setq modus-themes-paren-match '(bold underline intense))
```

Yes, the above snippet helps and I can see the character now. Thanks!

Seems like orange is indeed coming from spacemacs. See https://develop.spacemacs.org/doc/DOCUMENTATION.html#states where orange implies "normal mode

**Comment by protesilaos** [comment]
I see.  Thanks for the information!
