### ISSUE TITLE
undesirable colors in magit buffers on operandi

### ISSUE THREAD

**Issue by gitrj95** [protesilaos/modus-themes#18]
hi, prot. i hope this message finds you well. i have found somewhat of an undesirable color rendering given the typical conventions of magit. i am unsure as to whether this is more general, but it certainly occurs in these two scenarios:

when i check the magit diff in operandi, say, during a commit, the old lines (conventionally red) appear grey until i point point to within this section

when i need to apply a flag to an operation, eg a put force, the remaining, non-flag lines are not greyed out to indicate usage of the flags

neither of these cases presents when using vivendi. i am not sure if this is simply a byproduct of adherence to the AAA standard, but i found this to force me into using vivendi on most occasions

let me know what you think

**Comment by protesilaos** [comment]
Hello @gitrj95 and thanks for taking the time to report this!

> i have found somewhat of an undesirable color rendering given the
> typical conventions of magit. i am unsure as to whether this is more
> general, but it certainly occurs in these two scenarios:

This sounds like a bug and not something we would intentionally design.

> when i check the magit diff in operandi, say, during a commit, the old
> lines (conventionally red) appear grey until i point point to within
> this section

Can you please post a screenshot and/or describe how to reproduce the
issue?  I have been using Magit virtually every day and never noticed
anything like this.

Also, can you place the point over those grey areas and call the command
`describe-char` (bound to `C-u C-x =` by default)?  It will produce a
Help buffer which will reference the applicable face[s], if any, towards
the end of the information block.

> when i need to apply a flag to an operation, eg a put force, the
> remaining, non-flag lines are not greyed out to indicate usage of the
> flags

I do not understand this reference.  How do you flag an operation?  Is
this with some Magit command or git on the command-line?

> neither of these cases presents when using vivendi. i am not sure if
> this is simply a byproduct of adherence to the AAA standard, but i
> found this to force me into using vivendi on most occasions

This part is what surprises me because the two themes derive from the
same code (the shared modus-themes.el file).  So if there exists a
problem at the theme level, it should be present in both variants.  But
we will figure this out as we go.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by gitrj95** [comment]
> second part
you can ignore the second bit. i think this has something to do with the devices i am using. eg, i noticed this on my windows machine, but not my mac

insofar as the first part, hopefully these screenshots are useful:
<img width="1512" alt="Screen Shot 2022-01-18 at 2 42 30 PM" src="https://user-images.githubusercontent.com/68976909/150016161-6650ad3a-7c29-4e4b-8e89-d23de686fab6.png">

<img width="1512" alt="Screen Shot 2022-01-18 at 2 43 02 PM" src="https://user-images.githubusercontent.com/68976909/150016223-f7ecc875-c5ef-476d-8a7d-b43631a3d4c7.png">

<img width="1512" alt="Screen Shot 2022-01-18 at 2 43 46 PM" src="https://user-images.githubusercontent.com/68976909/150016249-d1e99dfa-13c5-4ca5-beb7-3

<img width="1512" alt="Screen Shot 2022-01-18 at 2 43 59 PM" src="https://user-images.githubusercontent.com/68976909/150016278-b924ffa3-39d5-4225-8dd9-204e91388c51.png">
86f87221868.png">

**Comment by protesilaos** [comment]
> hopefully these screenshots are useful

Yes, they are.  Thank you!

The problem here is that the terminal emulator you are using cannot accurately reproduce the underlying colour values.  Try the graphical (GUI) version of Emacs to see what I mean: almost all colours are different.

I don't know how to fix Kitty, or any terminal emulator for that matter, to show all colours correctly.

The Emacs manual has a section on the matter, though I cannot tell how useful it is (it does not seem trivial to me): <https://www.gnu.org/software/emacs/manual/html_mono/efaq.html#Colors-on-a-TTY>.

There is this thread that might provide some further clues: <https://stackoverflow.com/questions/14672875/true-color-24-bit-in-terminal-emacs>.

Another potentially useful resource: <https://github.com/termstandard/colors>.

**Comment by gitrj95** [comment]
great, thanks for your feedback. i'll do some digging and see if there's anything that doesn't require heavy hacking. i oscillate between kitty and alacritty... do you happen to know if the latter offers the needed colors?

**Comment by gitrj95** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44950#20

**Comment by protesilaos** [comment]
> great, thanks for your feedback. i'll do some digging and see if there's anything that doesn't require heavy hacking. i oscillate between kitty and alacritty... do you happen to know if the latter offers the needed colors?

I just gave alacritty a try: it still misrepresents colour values.  Xterm too.  This is one of the reasons why I only use GUI Emacs.

> https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44950#20

I read it and am not sure the underlying issue has been addressed.  I am building Emacs from source and am currently using the `--with-pgtk` flag.  The problem with colour reproduction on terminal emulators is not new and it persists.

**Comment by gitrj95** [comment]
i see. there seems to be some contention between the emacs developers and terminal developers as to who will cover the deficit--if i understood correctly

**Comment by gitrj95** [comment]
i see. makes sense

**Comment by protesilaos** [comment]
Hello again!

I have found a way to render colours properly inside my terminal emulator (Xterm).  I set the envrionment variable to `TERM=xterm-direct` and then it works as expected.  Here is Magit with a diff that highlights one hunk:

![2022-01-24_08:54:15_1923x1054](https://user-images.githubusercontent.com/12828033/150735881-2739db24-a965-49dd-bce5-846d282cf9fb.png)

Same principle for alacritty with `TERM=alacritty-direct`.  I get this:

![2022-01-24_08:58:27_1923x1054](https://user-images.githubusercontent.com/12828033/150736214-9c0a22b0-d650-4bf6-9414-47b15f76039a.png)

In the terminal type something like `toe -a | grep direct` to see if you get what you need.  On my end it returns `kitty-direct` as well.

**Comment by gitrj95** [comment]
thanks as always, prot. this is great

**Comment by protesilaos** [comment]
> thanks as always, prot. this is great 

You are welcome!  I will update the manual accordingly.

-- 
Protesilaos Stavrou
https://protesilaos.com
