### ISSUE TITLE
Indistinct background color in swiper candidates

### ISSUE THREAD

**Issue by wang1zhen** [protesilaos/modus-themes#26]
![image](https://user-images.githubusercontent.com/31798841/160830249-534be0f0-c07c-403e-b013-baea92220d1a.png)

The current selected candidate is somehow hard to distinguish in the swiper candidates due to the background color of org src blocks, it can be reproduced with following theme configurations:

```
(use-package modus-themes
      :init
      (setq modus-themes-bold-constructs t
            modus-themes-syntax '(alt-syntax green-strings yellow-comments)
            modus-themes-links '(neutral-underline background)
            modus-themes-hl-line '(intense)
            modus-themes-markup '(intense background)
            modus-themes-paren-match '(intense)
            modus-themes-org-blocks 'gray-background)
      :config
      (modus-themes-load-vivendi))
```

**Comment by protesilaos** [comment]
We can try asking Vertico's and Consult's maintainer (@minad).  Perhaps adding a priority to the overlay would address this issue where the background of an Org block overrides the currently selected line in the minibuffer?

**Comment by minad** [comment]
In Vertico the problem should not be as serious since the `vertico-current` face extends to the full width of the minibuffer. We cannot give `vertico-current` higher priority, since this would interfere with `modus-themes-completions` with `matches=background`. Therefore the `vertico-current` face is appended to the other faces. I consider this issue as WONTFIX in Vertico/Consult. Either disable fontification in `consult-line` via `consult-fontify-preserve=nil` or disable the background for org blocks by modifying `modus-themes-org-blocks`.

**Comment by protesilaos** [comment]
Thanks for the explanation!
