### ISSUE TITLE
Why are level 1 headers white in dark version?

### ISSUE THREAD

**Issue by Andre0991** [protesilaos/modus-themes#3]
Hi. First, thanks for creating modus-themes.

The issue is that level-1 org-mode/markdown/etc headers are white in the dark version of modus-themes, resulting in no color contrast compared to the body text.

Example:

![image](https://user-images.githubusercontent.com/7083061/120091027-7fd67a80-c0dd-11eb-9a6d-ad315fbe1cf3.png)

I'm sure this is customizable, I'm just wondering why this is the default.

**Comment by protesilaos** [comment]
Hello @Andre0991!

> thanks for creating modus-themes.

You are welcome!

> The issue is that level-1 org-mode/markdown/etc headers are white in
> the dark version of modus-themes, resulting in no color contrast
> compared to the body text.

The default for headings is to be simple, or close to a plain text
experience.  All headings are rendered in bold typography and use fairly
neutral colours.  Defaults are always tricky because they will not
satisfy everyone.  If the headigns were colourful out-of-the-box,
someone would ask why is that the default and not something more
subtle.  You get the idea.

Thankfully we have lots of customisation options (all are documented in
the manual---either evaluate `(info "(modus-themes) Top")` or visit
https://protesilaos.com/modus-themes)

You can opt for more colourful headings with this:

```elisp
(setq modus-themes-headings
      '((t . rainbow)))
```

There are a lot of options here.  For example, if you want all headings
to be colourful but without a bold weight:

```elisp
(setq modus-themes-headings
      '((t . rainbow-no-bold)))
```

All the styles documented in the doc string of `modus-themes-headings`
can be assigned to individual levels.  Like this:

```elisp
(setq modus-themes-headings
      '((1 . rainbow-section)           ; level 1 headings
        (2 . rainbow-line)              ; level 2
        (t . rainbow-no-bold)))         ; everything else
```

**Comment by Andre0991** [comment]
>The default for headings is to be simple, or close to a plain text
experience. All headings are rendered in bold typography and use fairly
neutral colours. Defaults are always tricky because they will not
satisfy everyone. If the headigns were colourful out-of-the-box,
someone would ask why is that the default and not something more
subtle. You get the idea.

That makes sense. I'd argue that since all the other heading levels have color, the first one could have a non-white color as well, in order to add a minimum contrast with the text (but still somewhat neutral, as you mentioned.)

However, as you said, defaults are hard, and it's just not possible to please everyone :)

Anyway, I'll use the customizations you mentioned. Thanks a lot for the explanation!

**Comment by protesilaos** [comment]
You are welcome!
