### ISSUE TITLE
Feature Request - iPython Notebooks

### ISSUE THREAD

**Issue by mtreca** [protesilaos/modus-themes#31]
Hi Prot, hope you are doing well.

Modus-themes is already extremely complete, but I would like to request the addition of faces from the [emacs-ipython-notebook](https://github.com/millejoh/emacs-ipython-notebook) package. The default doesn't really look great (see below):

<img width="725" alt="Screenshot 2022-05-23 at 11 10 59" src="https://user-images.githubusercontent.com/16440823/169785803-e5a04909-da05-440b-837b-6ab90b52905d.png">

Thank you for your work on modus themes.
Cheers,
Max.

**Comment by protesilaos** [comment]
Hello @mtreca!

> I would like to request the addition of faces from the
> [emacs-ipython-notebook](https://github.com/millejoh/emacs-ipython-notebook)
> package.

Sure!  Though I need your help to test this package.  How can I get a
buffer like the one you show in the screenshot?  I need it to test
things.

Right now, I would test something like this for regular input:

    (modus-themes-with-colors
      (set-face-attribute 'ein:basecell-input-area-face nil :background bg-dim))

Or this:

    (modus-themes-with-colors
      (set-face-attribute 'ein:basecell-input-area-face nil :background bg-alt))

For errors it would most likely be this:

    (modus-themes-with-colors
      (set-face-attribute 'ein:cell-output-stderr nil :background red-nuanced-bg))

> Thank you for your work on modus themes.

You are welcome!

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by mtreca** [comment]
Hi Prot.

On the Elisp side of things, the following should be enough to have a minimal working example:

```elisp
(use-package modus-themes
  :ensure t
  :config
  (setq x-underline-at-descent-line t)
  (setq modus-operandi-theme-distinct-org-blocks t)
  (setq modus-operandi-theme-faint-syntax t)
  (setq modus-operandi-theme-intense-paren-match t)
  (setq modus-operandi-theme-org-blocks 'greyscale)
  (load-theme 'modus-operandi t))

(use-package ein
  :ensure t)
```

As for content files, any .ipynb file should work (you can look [here](https://github.com/odewahn/ipynb-examples) for a simple collection of files), even though you would probably need to install a working Jupyter server in order to display notebooks properly, after starting a server using `ein:run`.

I can of course provide feedback to color choices you come up with for this package.

Don't hesitate if you require further information or help on my end.

Best,
Maxime

**Comment by protesilaos** [comment]
> Hi Prot.

Hello Maxime,

> On the Elisp side of things, the following should be enough to have a
> minimal working example:

I add the corresponding configurations for the current version of the
themes, because there have been some changes (please check the doc
string of each variable or the manual):

>   (setq modus-operandi-theme-faint-syntax t)

(setq modus-themes-syntax '(faint))

>   (setq modus-operandi-theme-intense-paren-match t)

(setq modus-themes-paren-match '(intense))

>   (setq modus-operandi-theme-org-blocks 'greyscale)

(setq modus-themes-org-blocks 'gray-background)

> As for content files, any .ipynb file should work (you can look
> [here](https://github.com/odewahn/ipynb-examples) for a simple
> collection of files), even though you would probably need to install a
> working Jupyter server in order to display notebooks properly, after
> starting a server using `ein:run`.
>
> I can of course provide feedback to color choices you come up with for
> this package.
>
> Don't hesitate if you require further information or help on my end.

I need help with the server.  I have zero knowledge on the matter.  If I
use my distro's package manager to search for "jupyter", "jupyter
server", etc. I get lots of results.  Are you using GNU/Linux?  If so,
which package do you use?

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by mtreca** [comment]
Thank you for the corrections regarding the modus themes, I did not have the time to track the recent changes.

Setting up a jupyter server is pretty straightforward if you have a linux distribution and the python programming language.

First, you should make sure that you have the python programming language and its packaging utility, `pip` installed. If not, you can obtain them using `sudo apt install python3-pip python3-dev` on Ubuntu or Debian-type distributions (assuming you are using apt as a package manager).

You can then install jupyter using the python package manager: `python3 -m pip install jupyter`. This should be enough to set it up. You do not need to start the server manually since the `ein` Emacs package normally takes care of it.

Note that I really opened this issue as a "nice to have" feature request, but that I do not consider it to be a priority at all.
It is hence honestly not too much of a problem if this setup work is too much from a time or bandwidth constraints given that adding these faces to modus themes is not really urgent.

Best,
Maxime

**Comment by protesilaos** [comment]
> You can then install jupyter using the python package manager:
> `python3 -m pip install jupyter`. This should be enough to set it
> up. You do not need to start the server manually since the `ein` Emacs
> package normally takes care of it.

I installed the packages.  Then M-x eir:run asks for a notebook
directory.  I assume the one with the ipynb-examples would do, so I
specified it.  The server failed to start.  I looked at the code and
found the command-line version.  Tried it in the shell prompt and got
this error:

```
~ $ jupyter notebook --notebook-dir=~/Git/miscellaneous/ipynb-examples/ --no-browser
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/usr/lib/python3.10/site-packages/notebook/__init__.py", line 27, in <module>
    from .nbextensions import install_nbextension
  File "/usr/lib/python3.10/site-packages/notebook/nbextensions.py", line 20, in <module>
    from ipython_genutils.py3compat import string_types, cast_unicode_py2
ModuleNotFoundError: No module named 'ipython_genutils'
```

> Note that I really opened this issue as a "nice to have" feature
> request, but that I do not consider it to be a priority at all.  It is
> hence honestly not too much of a problem if this setup work is too
> much from a time or bandwidth constraints given that adding these
> faces to modus themes is not really urgent.

Understood.  It will be nice to support this.

**Comment by mtreca** [comment]
Hmm, the repository I pointed you too might require additional packages in order to function. My bad.

I have created a very simple ipynb file that you can use. It is available [here](https://gist.github.com/mtreca/0b434437dbd870a5efa6e913231bccfa) . This should bypass the need for additional packages. If the package is still needed for some reason, `python3 -m pip install ipython` should take care of it.

Note that you can simply open the ipynb file in emacs, and call server start from the ein package directly, using `C-c C-o`. 

Thanks again and do not hesistate to ping me if you need further help.

**Comment by protesilaos** [comment]
Okay, I got it to work.  Thank you!  I am now experimenting with it.

Note this:

![2022-05-27_15:31:27_576x576](https://user-images.githubusercontent.com/12828033/170699766-b3fdf052-cdd5-4a27-bad3-30f53e8499fa.png)

That brown block at `----> 3 1/0` is a hardcoded colour.  I cannot change it by tweaking a face.  Upstream needs to do it.

More to follow.

**Comment by protesilaos** [comment]
Okay, I can fix that by applying a background.  Since it is an error, a faint red seems appropriate.

![2022-05-27_15:42:32_576x576](https://user-images.githubusercontent.com/12828033/170701374-2d1bb46a-a702-4bdb-b082-f94f8b318afe.png)

What do you think?

Note that I do not control the colours in that red block: they probably come directly from the terminal colours.

Also, I find that standard output does not need to have a special background (e.g. faint cyan).  The absence of a distinct background looks cleaner or less busy.

**Comment by mtreca** [comment]
I think the red block is the way to go, it draws attention while still being legible. I also agree regarding leaving standard output as is.

Regarding code blocks, could we use something like org-blocks ? Using a slightly dimmed background colour for source code, delimited by even slightly darker background lines.

<img width="255" alt="Screenshot 2022-05-27 at 15 10 13" src="https://user-images.githubusercontent.com/16440823/170705756-1b1060a8-3e43-4f88-b620-c5c7c3be565f.png">


More generally, I think using a pattern similar to what is used in org mode blocks would make sense and would make the theme consistent. Another last nitpick, the top line of your screenshot shows the current kernel (Python3) in a smaller font than the rest. Could this be fixed by the theme?

**Comment by protesilaos** [comment]
> I think the red block is the way to go, it draws attention while still
> being legible. I also agree regarding leaving standard output as is.

Good!

> Regarding code blocks, could we use something like org-blocks ? Using
> a slightly dimmed background colour for source code, delimited by even
> slightly darker background lines.

Yes for the background.  Though the delimiters are trickier because we
do not have the equivalent of BEGIN/END that Org has.  Maybe we could
achieve a similar effect by tweaking the prompts like `In [1]:`?

Also, EIN seems to support different types of source blocks: generic,
markdown, html, codecell.  I think only html and codecell should count
as "code blocks" and get a background.  The others should use the main
background.  Or should they all be the same?

> More generally, I think using a pattern similar to what is used in org
> mode blocks would make sense and would make the theme consistent.

Agreed!

> Another last nitpick, the top line of your screenshot shows the
> current kernel (Python3) in a smaller font than the rest. Could this
> be fixed by the theme?

I already changed that to use the main font size.  I do not like 0.8
height in the themes, because it often is hard to read (and thus
contradicts our legibility target).

What I have right now:

![2022-05-27_16:51:52_632x656](https://user-images.githubusercontent.com/12828033/170713992-4a14f24c-48eb-4109-a3ec-9647546ad7be.png)

**Comment by protesilaos** [comment]
Just tested: we cannot use the prompts as delimiters because they do not extend.  Here I colour them blue to see what I mean:

![2022-05-27_17:03:35_576x576](https://user-images.githubusercontent.com/12828033/170715099-c9ac7b11-98e5-4314-a8fa-5d3f436adf2c.png)

For a face to accept `:extend t` it needs to include a newline.  I cannot handle this at the theme level.

**Comment by mtreca** [comment]
I was about to suggest `:extend t`, but if it doesn't work that's ok. It already looks great, thanks!

**Comment by protesilaos** [comment]
Okay, I will push the changes now.  If you think we can improve them further, we shall do it.

**Comment by mtreca** [comment]
That's perfect. Thanks a lot for your reactivity and for maintaining the modus-themes.

I think we can close this issue for now. If anyone spots any issues or useful additions to the theme, feel free to reopen it.
